#!/bin/sh

set -u

myself=$0

# Default values for global options.
sda_config=s3cmd.conf		# --sda-config pathname
sda_key=crypt4gh_key.pub	# --sda-key pathname

cmd_exists () {
	command -v "$1" >/dev/null 2>&1
}

upload () {
	# Encrypt+upload using sda-cli.

	if ! cmd_exists sda-cli; then
		cat <<-'NOTFOUND_ERROR' >&2
		Can't find sda-cli in your $PATH.  Please, install it
		from https://github.com/NBISweden/sda-cli and make it
		available in one of the directories in $PATH.
		NOTFOUND_ERROR
		exit 1
	fi

	for pathname do
		case $pathname in
			*.c4gh)
				# Don't encrypt.
				set --
				;;
			*)
				set -- --encrypt-with-key "$sda_key"
		esac

		sda-cli upload -config "$sda_config" "$@" "$pathname"
	done
}

ingest () {
	:
}

accession () {
	:
}

dataset () {
	:
}

usage () {
	case ${1-} in
		upload|ingest|accession|dataset)
			"usage_$1"
			;;
		"")
			usage_general
			;;
		*)
			usage_general
			return 1
	esac
}

usage_general () {
cat <<-USAGE_GENERAL
	General synopsis:
	    $myself [GLOBAL OPTIONS] [help] {upload|ingest|accession|dataset} [ARGUMENTS]

	Global options:
	    --sda-config pathname	SDA S3 configuration file	Default: $sda_config
	    --sda-key pathname		SDA CRYPT4GH public key file	Default: $sda_key

	Specific synopsis:
	    $myself help

	    $myself [...] upload pathname [pathname...]
	    $myself help upload

	    $myself [...] ingest pathname [pathname...]
	    $myself help ingest

	    $myself [...] accession pathname accessionID
	    $myself [...] accession pathname
	    $myself [...] accession
	    $myself help accession

	    $myself [...] dataset [--add] datasetID accessionID [accessionID...]
	    $myself [...] dataset [--add] datasetID pathname [pathname...]
	    $myself [...] dataset datasetID
	    $myself help dataset

	USAGE_GENERAL
}

# Handle global options.
while true; do
	case ${1-} in
		--sda-config)
			sda_config=$2
			;;
		--sda-key)
			sda_key=$2
			;;
		*)
			break
	esac
	shift 2
done

# Handle sub-comands.
case ${1-} in
	upload|ingest|accession|dataset)
		"$@"
		;;
	help)
		shift
		usage "$@"
		;;
	*)
		usage
		exit 1
esac
